[2023-02-18T01:02:13.647+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: booking_ingestion.load_data manual__2023-02-18T01:02:09.951436+00:00 [queued]>
[2023-02-18T01:02:13.654+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: booking_ingestion.load_data manual__2023-02-18T01:02:09.951436+00:00 [queued]>
[2023-02-18T01:02:13.661+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T01:02:13.662+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-18T01:02:13.663+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T01:02:13.672+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data> on 2023-02-18 01:02:09.951436+00:00
[2023-02-18T01:02:13.678+0000] {standard_task_runner.py:55} INFO - Started process 1609 to run task
[2023-02-18T01:02:13.681+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'load_data', 'manual__2023-02-18T01:02:09.951436+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/main.py', '--cfg-path', '/tmp/tmpdbu3q7kf']
[2023-02-18T01:02:13.683+0000] {standard_task_runner.py:83} INFO - Job 283: Subtask load_data
[2023-02-18T01:02:13.746+0000] {task_command.py:388} INFO - Running <TaskInstance: booking_ingestion.load_data manual__2023-02-18T01:02:09.951436+00:00 [running]> on host d92f32803fb9
[2023-02-18T01:02:13.800+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-18T01:02:09.951436+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-18T01:02:09.951436+00:00
[2023-02-18T01:02:13.821+0000] {base.py:73} INFO - Using connection ID 'postgres_db' for task execution.
[2023-02-18T01:02:13.828+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 52, in load_data
    postgres_sql_upload.insert_rows('booking_record', records)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "c"
LINE 1: INSERT INTO booking_record  VALUES ('c','l','i','e','n','t',...
                                            ^

[2023-02-18T01:02:13.839+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=load_data, execution_date=20230218T010209, start_date=20230218T010213, end_date=20230218T010213
[2023-02-18T01:02:13.848+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 283 for task load_data (invalid input syntax for type integer: "c"
LINE 1: INSERT INTO booking_record  VALUES ('c','l','i','e','n','t',...
                                            ^
; 1609)
[2023-02-18T01:02:13.896+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-18T01:02:13.912+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
